### ISSUE TITLE
Does this repo include RoNIN_3D mentioned in the paper?

### ISSUE THREAD

**Issue by tonyke1993** [CathIAS/TLIO#16]
If so, could you provide the corresponding command?

**Comment by CathIAS** [comment]
Yes! Apologies for the delay. RoNIN 3D baseline is essentially the network part before the filter, and the metrics and plots can be obtained through test.py:
```
python3 src/main_net.py \
--mode test \
--root_dir data/Dataset \
--test_list data/Dataset/test.txt \
--model_path models/resnet/checkpoint_*.pt \
--out_dir test_outputs \
--save_plot
```
Having `--save_plot` option on will save the concatenated trajectories and output visualization into the output directory.

**Comment by tonyke1993** [comment]
I see. Thank you!
