### ISSUE TITLE
TLIO initialization

### ISSUE THREAD

**Issue by tflucas** [CathIAS/TLIO#21]
Thank you for sharing the code. 
I have prepared a dataset and obtained a trained model. 
When I test the TLIO system by using a new sequence with no ground-truth file,   how can I obtain an initial state(R v p ba bg) to start the EKF filter. 
Besides, how can I rotate raw IMU data in IMU local frame to obtain IMU samples in a gravity-aligned frame?

**Comment by CathIAS** [comment]
If you do not have ground truth or other odometry system running, make an initial guess as accurate as possible and hopefully the filter will converge.
In TLIO, this rotation comes from the filter estimates.

**Comment by patrickctrf** [comment]
> Thank you for sharing the code.
> I have prepared a dataset and obtained a trained model.
> When I test the TLIO system by using a new sequence with no ground-truth file, how can I obtain an initial state(R v p ba bg) to start the EKF filter.
> Besides, how can I rotate raw IMU data in IMU local frame to obtain IMU samples in a gravity-aligned frame?

@tflucas Could you share the files you used to train the model? Thanks

**Comment by CathIAS** [comment]
@patrickctrf @tflucas  For txt file formats please refer to the documentation. For further questions please open a new issue.
