### ISSUE TITLE
Measurement update

### ISSUE THREAD

**Issue by ccwss1232** [CathIAS/TLIO#23]
Thank you for your excellent paper.
After reading your paper, I have two questions: 1. How does the updated measurement function H (x) come from? Can I interpret it as a pseudo-measurement? 2. How was the partial derivative of Formula (15) calculated? Could you give the specific derivation steps?

best wishes

**Comment by CathIAS** [comment]
Hi! Thanks for your questions.
1. The measurement matrix H comes from the linear derivative of the measurement against the state, and from equation (14), there are only non-zero values in the matrix in three blocks corresponding to the rotation and position in i and j. It is not a pseudo measurement and the actual measurement is the network output displacement between state i and state j.
2. I attached an appendix file with the detailed derivations to this question.
[tlio-appendix.pdf](https://github.com/CathIAS/TLIO/files/6542714/tlio-appendix.pdf)

**Comment by ccwss1232** [comment]
Hello, author, thank you for your reply. I still have some details to ask you. Do you have QQ and can you add me as a friend?  1102165192
