### ISSUE TITLE
The vio-displacement is used as the regressed target, why can the velocity be ignored?

### ISSUE THREAD

**Issue by DHNicoles** [CathIAS/TLIO#26]
Hi, If imu moves at a constant speed at different speeds, the imu_raw data will be the same. Then the neural network will output the same displacement while inferencing. So why the velocity could be ignored when training the network? 
I'm not sure if the question is clearly stated, thank you in advance.

**Comment by CathIAS** [comment]
Hi @DHNicoles,
Thank you for the question and my sincere apologies for the delay in my reply. 
Your observation is correct.
The removal of initial velocity from the input is to force the network to not learn the integration function which mathematically is known to us, but learn the human movement patterns instead. In pedestrian applications, these perfect constant speed situations do not naturally occur and what the network is looking for are features like steps and the way the steps are taken.

**Comment by DHNicoles** [comment]
Got it.
